sudo: required

services:
- docker

language:
  java

jdk:
- oraclejdk8

env:
  COMPOSE_VERSION: 1.4.1

before_install:
- curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /

script:
- docker-compose build
- docker-compose run test






