sudo: required

services:
- docker

language: java

before_install:
- chmod +x gradlew

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

jdk:
- oraclejdk8

script:
- ./gradlew assembleRelease


after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -u $DOCKER_USER -p $DOCKER_PASS

#TAG
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

# AUTH SERVICE
- export AUTH_SERVICE=DyvakYA/authentication-service
- docker build -t $AUTH_SERVICE:$COMMIT ./authentication-service
- docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
- docker push $AUTH_SERVICE

# MAIN SERVICE
- export MAIN_SERVICE=DyvakYA/main-service
- docker build -t $MAIN_SERVICE:$COMMIT ./main-service
- docker tag $MAIN_SERVICE:$COMMIT $MAIN_SERVICE:$TAG
- docker push $MAIN_SERVICE


